server:
  port: 8766

feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
